linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
    - gci
run:
  timeout: 5m
linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments:
          - ["ID", "URL", "HTTP", "JSON", "API"]
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cecobask/imdb-trakt-sync)
    custom-order: true